### ISSUE TITLE
Service location

### ISSUE THREAD

**Issue by Oyabi** [iwayvietnam/zimbra-multi-tenancy#51]
Hi,

I try to add a server in your drupal addon configuration page but i get `Connection to zimbra server failed!` with every parameters that I try.
I'm sure that my admin user and admin password are correct but what must I put in `Service location` ?
I have try my server ip (in test) with port 80,7070,7071 in http and https but nothing. I always get that error message.

I have the lastest drupal 7 version and the master branch of your module.

Regards.

**Comment by nguyennv** [comment]
Hi Oyabi,
You goto Configuration -> Zimbra multi-tenancy settings, click "Enable debug" and save configuration.
Then you test connection to the zimbra server again.
After that you goto Report -> Recent log messages and show me all message type "zimbra" for debuging.

**Comment by Oyabi** [comment]
Hi, 
I have 3 lines in log : 
zimbra - AuthRequest : 
```
{"Header":{"context":{"_jsns":"urn:zimbra","format":"js"}},"Body":{"AuthRequest":{"_jsns":"urn:zimbraAdmin","name":"admin@testzimbra.mydomain.fr","password":"mypassword","persistAuthTokenCookie":true}}}
```
zimbra - AuthResponse is empty.
zimbra:
```
UnexpectedValueException: Error opening socket ssl://10.0.240.164:7071 in /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc:1665 Stack trace: #0 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc(1606): SoapResponse->_processResponse(Object(stdClass)) #1 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc(1925): SoapResponse->__construct(Object(stdClass)) #2 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.api.inc(752): HttpSoapClient->doRequest(Object(AuthRequest)) #3 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.api.inc(775): ZimbraAdminApi->auth('admin@testzimbr...', 'mypassword', NULL, NULL, NULL, true) #4 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.inc(145): ZimbraAdminApi->authByName('admin@testzimbr...', 'mypassword') #5 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.inc(38): zimbra_authentication_by_name(Object(ZimbraAdminApi), 'admin@testzimbr...', 'mypassword') #6 /var/www/html/sites/all/modules/zimbra-multi-tenancy/zmt_ui.module(574): zimbra_test_connection('https://10.0.24...', 'admin@testzimbr...', 'mypassword') #7 /var/www/html/includes/ajax.inc(398): ajax_zmt_server_test_connection(Array, Array) #8 /var/www/html/includes/menu.inc(527): ajax_form_callback() #9 /var/www/html/index.php(21): menu_execute_active_handler() #10 {main}
```

Thank you.

**Comment by nguyennv** [comment]
Hi Oyabi,
In zimbra multi tenancy, by default, this module use drupal_http_request of Drupal to connect to zimbra server. But is not allow self signed certificate.
To fix it, you need to install [chr](https://www.drupal.org/project/chr) module for self signed certificate allowing.

**Comment by Oyabi** [comment]
Hi, 
Ok now I have something in `zimbra - AuthResponse`, but I have got a new error in `zimbra`:
```
UnexpectedValueException: Error to parse reponse data: 
The zimbra connection input with some log.
```

I use zimbra 8.7.0, maybe they have made change in the login page/response.

Thank you.

**Comment by nguyennv** [comment]
Hi Oyabi,
The latest version of zimbra I've tested with this module is 8.6.0.

**Comment by Oyabi** [comment]
Hi,
Even with the prod server (8.6.0) I have an `Error parse response data`:
```
in /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc:1660 Stack trace: #0 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc(1606): SoapResponse->_processResponse(Object(stdClass)) #1 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.soap.inc(1925): SoapResponse->__construct(Object(stdClass)) #2 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.api.inc(752): HttpSoapClient->doRequest(Object(AuthRequest)) #3 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.api.inc(775): ZimbraAdminApi->auth('me@mydomain.fr', 'blablabla...', NULL, NULL, NULL, true) #4 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.inc(145): ZimbraAdminApi->authByName('me@mydomain.fr', 'blablabla...') #5 /var/www/html/sites/all/modules/zimbra-multi-tenancy/includes/zmt.zimbra.inc(38): zimbra_authentication_by_name(Object(ZimbraAdminApi), 'me@mydomain.fr', 'blablabla...') #6 /var/www/html/sites/all/modules/zimbra-multi-tenancy/zmt_ui.module(574): zimbra_test_connection('http://mail.mydomain...', 'me@mydomain.fr', 'blablabla...') #7 /var/www/html/includes/ajax.inc(398): ajax_zmt_server_test_connection(Array, Array) #8 /var/www/html/includes/menu.inc(527): ajax_form_callback() #9 /var/www/html/index.php(21): menu_execute_active_handler() #10 {main}
```
